spring:
  application:
    name: customer-api
server:
  port: 0
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}